# Generated by Django 6.0.5 on 2026-05-08 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('school_level', models.CharField(max_length=20)),
                ('interests', models.JSONField()),
                ('teamwork', models.IntegerField()),
                ('physical_activity', models.IntegerField()),
                ('problem_solving', models.IntegerField()),
                ('creativity', models.IntegerField()),
                ('performing', models.IntegerField()),
                ('structured_env', models.IntegerField()),
                ('helping_others', models.IntegerField()),
                ('commitment_hours', models.CharField(max_length=20)),
                ('schedule', models.CharField(max_length=20)),
                ('participated_before', models.CharField(max_length=5)),
                ('skill_level', models.CharField(max_length=20)),
                ('activity_type', models.CharField(max_length=20)),
                ('constraints', models.JSONField()),
                ('goal', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
